### PR TITLE
Fix for #79: Ability to change the configured software

### PR DESCRIPTION
**Pull request by Thorium**
Now you can actually use AppSettingsProvider from *.fsx scripts and F# Interactive.
This is example code:

        #I @"./../packages/FSharp.Configuration/lib/net40"
        #r @"./../packages/FSharp.Configuration/lib/net40/FSharp.Configuration.dll"
        #r "System.Configuration.dll"

        type Settings = FSharp.Configuration.AppSettings<"app.config">

        let path = System.IO.Path.Combine [|__SOURCE_DIRECTORY__ ; "bin"; "myProject.exe" |]

        Settings.SelectExecutableFile path

        Settings.MyProperty

### CODE REVIEW

**Comment by Thorium** [comment]
This is not the first build to have Travis broken.

Ping #79

**Comment by vasily-kirichenko** [comment]
Thanks for contribution! Could you add some tests?

**Comment by Thorium** [comment]
I will but this needs a bit more work as the tests seems to run in parallel and the current AppConfigProvider doesn't handle multiple parallel providers.
Also I have to fix the path resolution to type constructor to work also with Mono if you ever plan to get both Travis and AppVeyor to run unit tests.

**Comment by Thorium** [comment]
I think this would be ready for merge. Or is there something else still?

**Comment by vasily-kirichenko** [comment]
The tests are not compiled:

image

**Comment by Thorium** [comment]
Did you do a full build?

**Comment by forki** [comment]
please rebase on master - I fixed the underlying travis issue.

**Comment by Thorium** [comment]
This is also workaround for issue #16

**Comment by vasily-kirichenko** [comment]
Published in 0.5.8

**Pull request merged**
