### PR TITLE
Added project dependency to SharpYaml

### PR DESCRIPTION
**Pull request by sergey-tihon**
Fix for https://github.com/fsprojects/FSharp.Configuration/issues/76
Get SharpYaml from NuGet but pack dll inside of FSharp.Configuration NuGet package

### CODE REVIEW

**Comment by sergey-tihon** [comment]
@forki Do you know how to fix it on Mono? Strange error...

> Paket failed with:
	Error during extraction of /Users/travis/build/fsprojects/FSharp.Configuration/packages/SharpYaml/SharpYaml.1.5.2.nupkg.
Message: The requested feature is not implemented.
 In rare cases a firewall might have blocked the download. Please look into the file and see if it contains text with further information.
StackTrace:
    at Paket.NuGetV2+ExtractPackage@353-7.Invoke (System.String message) [0x00000] in <filename unknown>:0

**Comment by sergey-tihon** [comment]
Founld https://github.com/fsharp/FAKE/issues/81

**Comment by vasily-kirichenko** [comment]
i hope you have tested it on real world projects in design, compile and runtime? On existing and on created from scratch projects? In VS 2012, 2013 and 2015?

**Comment by sergey-tihon** [comment]
Haha, definitely not. I even do not have VS 2012 and VS 2013.
Nothing changed except binary of `Sharp Xaml.dll` inside the package.
If you worry we could release it with `-beta` suffix into pre-release channel and let people test in different IDEs

**Comment by forki** [comment]
does this solve #76?
Can you please rebase on master?

**Comment by sergey-tihon** [comment]
This PR just remove `SharpYaml.dll` from `lib` folder and restore latest version from `NuGet`.

**Comment by vasily-kirichenko** [comment]
Published in 0.5.8

**Pull request merged**
