### PR TITLE
Fixed a round trip serialization problem in SharpYaml 

### PR DESCRIPTION
**Pull request by Turee**
SharpYaml deserialized a string "1.0" as double, then serialized it to string "1". The string "1" was deserialized as integer resulting changed type of the field.

### CODE REVIEW

**Comment by forki** [comment]
what about using https://www.nuget.org/packages/SharpYaml/ instead?

**Comment by vasily-kirichenko** [comment]
We do use SharpYaml.

**Comment by forki** [comment]
Yep but I meant: shouldn't we use the nuget package instead of putting a dll in lib folder? Or is this a different thing

**Comment by Turee** [comment]
I'm for the nuget also. I made a pull request to SharpYaml for the bugfix: https://github.com/xoofx/SharpYaml/pull/8

**Comment by vasily-kirichenko** [comment]
Ah. Initially I put the dll because I made a couple of patches but the author of SharpYaml did not fix publish the package for a long time. I agree that NuGet package dependency is much better.

**Comment by Turee** [comment]
Alright that explains it :).

**Pull request merged**
