### PR TITLE
Fix ResX provider

### LINKED ISSUE #73: ResXProvider cannot read any values from the embedded resource.
At runtime, ResXProvider references the local path of the build environment.
ResXProvider generates the following code.

``` fsharp
ResXProvider.readValue "E:\\repos\\FsYaml2\\FsYaml\\Resources.resx" "mustBeSequence" :?> string
```

An exception occurs because Resources.resx does not exist at runtime.

Similar to https://github.com/fsprojects/FSharp.Configuration/issues/46

### PR DESCRIPTION
**Pull request by efoerster**
The current implementation of the ResX provider tries to read the .resx file at runtime and therefore fails when being deployed. I changed the implementation to be more in line with the C# one.

This commit fixes #73 and #46.

### CODE REVIEW

**Comment by dsyme** [comment]
This looks great

@forki @vasily-kirichenko what do you think?

**Comment by vasily-kirichenko** [comment]
I don't know. I'm not the author and I've never used it. Maybe someone who is using it could test this PR?

**Comment by dsyme** [comment]
@dtchepak any ideas?

**Comment by dtchepak** [comment]
@dsyme Sorry Don, i'm in the same boat as @vasily-kirichenko.

**Comment by forki** [comment]
So to sum up: we don't have a maintainer using this thing ;-)

**Comment by rojepp** [comment]
I nominate @efoerster. :)
Code changes look great at a glance.
Nice touch updating the screenshot. Easily overlooked.

**Pull request merged**
