### PR TITLE
Fix ResXProvider

### PR DESCRIPTION
**Pull request by bleis-tift**

### CODE REVIEW

**Comment by bleis-tift** [comment]
@forki @vasily-kirichenko @dtchepak Is this repository maintained?

**Comment by vasily-kirichenko** [comment]
I was not the person who implemented ResX provider and I don't use it => cannot test your PR.

**Comment by forki** [comment]
did you write new tests? What was broken?

**Comment by vasily-kirichenko** [comment]
@bleis-tift Please, rebase it on master. It would by much easier to see what's changed if you split this PR into two: one with cosmetic changes (removing line endings and the like), and the second with actual fix.

**Pull request closed without merging**
